# Generated by Django 4.1.7 on 2023-03-19 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Date',
            field=models.CharField(default=None, max_length=300),
        ),
    ]
