# Generated by Django 4.1.7 on 2023-03-19 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_alter_post_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentUser', models.CharField(max_length=64)),
                ('followUser', models.CharField(max_length=64)),
            ],
        ),
    ]
