# Generated by Django 4.1.7 on 2023-03-21 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_post_likedusers_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likedUsers',
        ),
    ]
